services:
  neo4j:
    image: neo4j:5-community
    container_name: grafopptak-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/grafopptak123
      - NEO4J_dbms_memory_pagecache_size=512M
      - NEO4J_dbms_memory_heap_initial__size=512M
      - NEO4J_dbms_memory_heap_max__size=1G
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:7474"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - grafopptak-network

  app:
    image: node:20-alpine
    container_name: grafopptak-app
    working_dir: /app
    ports:
      - "3000:3000"
      - "80:3000"
      - "8080:3000"
    environment:
      - NODE_ENV=production
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=grafopptak123
      - HOST=0.0.0.0
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      neo4j:
        condition: service_healthy
    command: npm start
    networks:
      - grafopptak-network

volumes:
  neo4j_data:
  neo4j_logs:

networks:
  grafopptak-network:
    driver: bridge