version: '3.8'

services:
  neo4j:
    image: neo4j:5-community
    container_name: grafopptak-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_memory_heap_initial__size=512M
      - NEO4J_dbms_memory_heap_max__size=1G
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grafopptak-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=
    depends_on:
      - neo4j
    command: sh -c "sleep 10 && npm start"

volumes:
  neo4j_data:
  neo4j_logs: