version: '3.8'

services:
  # Neo4j Database
  neo4j:
    image: neo4j:5-community
    container_name: grafopptak-neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j_data:/data

  # Next.js App
  app:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: grafopptak-app
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "80:3000"
      - "8080:3000"
    environment:
      - NODE_ENV=production
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
    depends_on:
      - neo4j

volumes:
  neo4j_data: